version: '3.3'
services:
  tor-wordpress:
    container_name: tor-wordpress
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./web/www:/var/www/html
    networks: 
      - tor-public
  tor-db:
    container_name: tor-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - tor-public
  tor:
    container_name: tor
    image: ghcr.io/antyung88/tor-wordpress:stable
    restart: always
    volumes:
      - ./web:/web
    networks:
      - tor-public

networks:
  tor-public:
    external: true
