version: '3.3'
services:
  tor-wordpress:
    container_name: tor-wordpress
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./web/www:/var/www/html
  tor-db:
    container_name: tor-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
  tor:
    container_name: tor
    image: ghcr.io/antyung88/tor-wordpress:stable
    restart: always
    volumes:
      - ./web:/web